# Site settings
title: Ameya School of Dance
email: ezoperationinc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ameya School of Dance, founded in 2017 by Sushmita Dutta, is a premier dance school in Saskatoon, SK, Canada. The school offers training in Indian Classical and Bollywood dance, blending tradition with modern performance styles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ezopinc.github.io/ameya_school/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ezopinc

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
paginate: 5
paginate_path: "/page:num/" # page will be /page2/, /page3/, ...
